framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            email_priority_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    # Messenger will create then send to this exchange
                    exchange:
                        name: email
                        type: direct
                        default_publish_routing_key: low
                    # Messenger will create this queue & add binding keys
                    # The worker will know to consume from this queue
                    queues:
                        emails_low:
                            binding_keys: [low]
                retry_strategy:
                    max_retries: 6
                    delay: 60000 # 1 minute in milliseconds
                    multiplier: 2 # Double the time between each attempt
            email_priority_normal:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    # Messenger will create then send to this exchange
                    exchange:
                        name: email
                        type: direct
                        default_publish_routing_key: normal
                    # Messenger will create this queue & add binding keys
                    # The worker will know to consume from this queue
                    queues:
                        emails_normal:
                            binding_keys: [normal]
                retry_strategy:
                    max_retries: 6
                    delay: 60000 # 1 minute in milliseconds
                    multiplier: 2 # Double the time between each attempt
            email_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: email
                        type: direct
                        default_publish_routing_key: high
                    queues:
                        emails_high:
                            binding_keys: [high]
                retry_strategy:
                    max_retries: 6
                    delay: 60000 # 1 minute in milliseconds
                    multiplier: 2 # Double the time between each attempt
        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            App\Message\EmailPasswordResetLink: email_priority_high
            App\Message\UserApprove: email_priority_high
            App\Message\ContactSubmit: email_priority_normal
            App\Message\UserNotificationMessage: email_priority_normal
            App\Message\BulkNotificationMessage: email_priority_normal
