security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        

    access_control:
        - { path: ^/forgot_password, roles: PUBLIC_ACCESS }
        - { path: ^/notify, roles: PUBLIC_ACCESS }
        - { path: ^/unsubscribe/, roles: PUBLIC_ACCESS }
        - { path: ^/pages, roles: PUBLIC_ACCESS }
        - { path: ^/ipg, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/docs, roles: PUBLIC_ACCESS }
        - { path: ^/token/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/contacts, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ranks, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
        - { path: ^/, roles: PUBLIC_ACCESS }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
