    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
security:
    firewalls:
        services:
            pattern: ^/(ipg|notify)
            stateless: true
            lazy: true
            security: false
        login:
            pattern: ^/token/login
            stateless: true
            json_login:
                check_path: /token/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            stateless: true
            entry_point: jwt
            json_login:
                check_path: app_login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            refresh_jwt:
                check_path: api_token_refresh
            jwt: ~
            logout:
                path: api_token_logout