security:
    firewalls:
        refresh:
            pattern: ^/token/refresh
            stateless: true
            lazy: true
            security: false
        services:
            pattern: ^/(ipg|notify)
            stateless: true
            lazy: true
            security: false
        main:
            lazy: true
            security: true
            provider: app_user_provider
            json_login:
                check_path: app_login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            logout:
                path: app_logout
            custom_authenticators:
                - lexik_jwt_authentication.jwt_token_authenticator